### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ctampan** [Rajesh2459/Little_lemon_booking_table-main#1]
Hello, sorry to reach you this way. Do you mind if you review my project too?

**Comment by Rajesh2459** [comment]
link

**Comment by Rajesh2459** [comment]
> Hello, sorry to reach you this way. Do you mind if you review my project too?

link review

**Comment by ctampan** [comment]
> > Hello, sorry to reach you this way. Do you mind if you review my project too?
> 
> link review

Thank you for your response, fortunately, my assignment has been reviewed :D
